# Tensorflow 기초 공부

<br/>

참고

elice - 텐서플로우와 인공신경망

## 텐서플로우(Tensorflow)

- 유연하고, 효율적이며, 확장성이 있는 딥러닝 프레임워크

- 대형 클러스터 컴퓨터부터 스마트폰까지 다양한 디바이스에서 동작

- 지원하는 언어: Python2/3, C/C++ 등

## 텐서(Tensor) ?

- Tensor = Multidimensional Arrays = Data

- 딥러닝에서 텐서는 다차원 배열로 나타내는 데이터

- 예를 들어, RGB 이미지는 삼차원 배열로 나타나는 텐서

## 플로우(Flow) ?

- 플로우는 데이터의 흐름을 의미

- 텐서플로우에서 계산은 데이터 플로우 그래프로 수행

- 그래프를 따라 데이터가 노드를 거쳐 흘러가면서 계산


<br/>

## 텐서 + 플로우

- 딥러닝에서 데이터를 의미하는 텐서(Tensor)와 데이터 플로우 그래프를 따라 연산이 수행되는 형태(Flow)의 합

# Tensorflow 기초 사용법

In [9]:
import tensorflow as tf

## 상수 선언 하기

In [10]:
# 상수형 텐서 선언
value = 2
a = tf.constant(value)

print(a)

tf.Tensor(2, shape=(), dtype=int32)


```
tf.constant(value, dtype=None, shape=None, name=None)
```

<br/>

value: 반환되는 상수값

shape: Tensor의 차원

dtype: 반환되는 Tensor 타입

name: 상수 이름

In [11]:
# 모든 원소 값이 0인 Tensor 생성
shape = (3, 3)
b = tf.zeros(shape, dtype=tf.float32, name=None)
print(b)

# 모든 원소 값이 1인 Tensor 생성
shape = (3, 3)
c = tf.ones(shape, dtype=tf.float32, name=None)
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


## 시퀀스 선언 하기

In [16]:
# start에서 stop까지 증가하는 num 개수 데이터
start = 1.0
stop = 10.0
num = 4

d = tf.linspace(start, stop, num)
print(d)

tf.Tensor([ 1.  4.  7. 10.], shape=(4,), dtype=float32)


```
tf.linspace(start, stop, num, name=None)
```

<br/>

start: 시작 값

stop: 끝 값

num: 생성할 데이터 개수

name: 시퀀스 이름

In [18]:
# start에서 stop까지 delta씩 증가하는 데이터
start = 1
e = tf.range(start, limit=10, delta=2)
print(e)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


```
tf.range(start, limit=None, delta=None, name=None)
```

start: 시작 값

limit: 끝 값

delta: 증가량

name: 시퀀스 이름

## 난수 선언 하기

In [19]:
# 정규분포 생성
shape = (3, 3)
f = tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name='normal')
print(f)

# 균등분포 생성
tf.random.uniform(shape, minval=10, maxval=None, dtype=tf.float32, seed=None, name='uniform')

tf.Tensor(
[[ 0.5936705  -0.60002565 -0.48701406]
 [ 0.21864748 -0.19882569 -1.059637  ]
 [-0.38632095  1.2279316  -0.3273219 ]], shape=(3, 3), dtype=float32)


<tf.Tensor: id=67, shape=(3, 3), dtype=float32, numpy=
array([[8.759666 , 3.7643285, 2.7700844],
       [8.465096 , 4.2958794, 3.7422423],
       [5.1935124, 7.6073804, 9.781977 ]], dtype=float32)>